// <auto-generated />
using System;
using ISNogometniStadion.WebAPI.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ISNogometniStadion.WebAPI.Migrations
{
    [DbContext(typeof(ISNogometniStadionContext))]
    [Migration("20190715221813_dodatakKorisnicima")]
    partial class dodatakKorisnicima
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ISNogometniStadion.Model.Drzava", b =>
                {
                    b.Property<int>("DrzavaID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Naziv");

                    b.HasKey("DrzavaID");

                    b.ToTable("Drzave");
                });

            modelBuilder.Entity("ISNogometniStadion.Model.Grad", b =>
                {
                    b.Property<int>("GradID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("DrzavaID");

                    b.Property<string>("Naziv");

                    b.HasKey("GradID");

                    b.HasIndex("DrzavaID");

                    b.ToTable("Gradovi");
                });

            modelBuilder.Entity("ISNogometniStadion.Model.Korisnik", b =>
                {
                    b.Property<int>("KorisnikID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DatumRodjenja");

                    b.Property<int>("GradID");

                    b.Property<string>("Ime");

                    b.Property<string>("Prezime");

                    b.Property<string>("email");

                    b.Property<string>("korisnickoIme");

                    b.Property<string>("lozinka");

                    b.Property<string>("telefon");

                    b.HasKey("KorisnikID");

                    b.HasIndex("GradID");

                    b.ToTable("Korisnici");
                });

            modelBuilder.Entity("ISNogometniStadion.Model.Sjedalo", b =>
                {
                    b.Property<int>("SjedaloID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Oznaka");

                    b.Property<int>("TribinaID");

                    b.HasKey("SjedaloID");

                    b.HasIndex("TribinaID");

                    b.ToTable("Sjedala");
                });

            modelBuilder.Entity("ISNogometniStadion.Model.Stadion", b =>
                {
                    b.Property<int>("StadionID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("GradID");

                    b.Property<string>("Naziv");

                    b.HasKey("StadionID");

                    b.HasIndex("GradID");

                    b.ToTable("Stadioni");
                });

            modelBuilder.Entity("ISNogometniStadion.Model.Tim", b =>
                {
                    b.Property<int>("TimID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("GradID");

                    b.Property<string>("Naziv");

                    b.Property<string>("Opis");

                    b.HasKey("TimID");

                    b.HasIndex("GradID");

                    b.ToTable("Timovi");
                });

            modelBuilder.Entity("ISNogometniStadion.Model.Tribina", b =>
                {
                    b.Property<int>("TribinaID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Naziv");

                    b.Property<int>("StadionID");

                    b.Property<int?>("StadionID)");

                    b.HasKey("TribinaID");

                    b.HasIndex("StadionID)");

                    b.ToTable("Tribine");
                });

            modelBuilder.Entity("ISNogometniStadion.Model.Ulaznica", b =>
                {
                    b.Property<int>("UlaznicaID");

                    b.Property<int>("UtakmicaID");

                    b.Property<int>("SjedaloID");

                    b.Property<DateTime>("DatumKupnje");

                    b.Property<int>("KorisnikID");

                    b.Property<DateTime>("VrijemeKupnje");

                    b.HasKey("UlaznicaID", "UtakmicaID", "SjedaloID");

                    b.HasIndex("KorisnikID");

                    b.HasIndex("SjedaloID")
                        .IsUnique();

                    b.HasIndex("UtakmicaID");

                    b.ToTable("Ulaznice");
                });

            modelBuilder.Entity("ISNogometniStadion.Model.Utakmica", b =>
                {
                    b.Property<int>("UtakmicaID");

                    b.Property<int>("DomaciTimID");

                    b.Property<int>("GostujuciTimID");

                    b.Property<DateTime>("DatumOdigravanja");

                    b.Property<int>("StadionID");

                    b.Property<DateTime>("VrijemeOdigravanja");

                    b.HasKey("UtakmicaID", "DomaciTimID", "GostujuciTimID");

                    b.HasIndex("DomaciTimID");

                    b.HasIndex("GostujuciTimID");

                    b.HasIndex("StadionID");

                    b.ToTable("Utakmice");
                });

            modelBuilder.Entity("ISNogometniStadion.Model.Grad", b =>
                {
                    b.HasOne("ISNogometniStadion.Model.Drzava", "Drzava")
                        .WithMany()
                        .HasForeignKey("DrzavaID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("ISNogometniStadion.Model.Korisnik", b =>
                {
                    b.HasOne("ISNogometniStadion.Model.Grad", "Grad")
                        .WithMany()
                        .HasForeignKey("GradID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("ISNogometniStadion.Model.Sjedalo", b =>
                {
                    b.HasOne("ISNogometniStadion.Model.Tribina", "Tribina")
                        .WithMany()
                        .HasForeignKey("TribinaID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("ISNogometniStadion.Model.Stadion", b =>
                {
                    b.HasOne("ISNogometniStadion.Model.Grad", "Grad")
                        .WithMany()
                        .HasForeignKey("GradID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("ISNogometniStadion.Model.Tim", b =>
                {
                    b.HasOne("ISNogometniStadion.Model.Grad", "Grad")
                        .WithMany()
                        .HasForeignKey("GradID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("ISNogometniStadion.Model.Tribina", b =>
                {
                    b.HasOne("ISNogometniStadion.Model.Stadion", "Stadion")
                        .WithMany()
                        .HasForeignKey("StadionID)");
                });

            modelBuilder.Entity("ISNogometniStadion.Model.Ulaznica", b =>
                {
                    b.HasOne("ISNogometniStadion.Model.Korisnik", "korisnik")
                        .WithMany()
                        .HasForeignKey("KorisnikID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("ISNogometniStadion.Model.Sjedalo", "sjedalo")
                        .WithOne("ulaznica")
                        .HasForeignKey("ISNogometniStadion.Model.Ulaznica", "SjedaloID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("ISNogometniStadion.Model.Utakmica", "utakmica")
                        .WithMany()
                        .HasForeignKey("UtakmicaID")
                        .HasPrincipalKey("UtakmicaID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("ISNogometniStadion.Model.Utakmica", b =>
                {
                    b.HasOne("ISNogometniStadion.Model.Tim", "DomaciTim")
                        .WithMany()
                        .HasForeignKey("DomaciTimID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("ISNogometniStadion.Model.Tim", "GostujuciTim")
                        .WithMany()
                        .HasForeignKey("GostujuciTimID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("ISNogometniStadion.Model.Stadion", "stadion")
                        .WithMany()
                        .HasForeignKey("StadionID")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
